import i1 from "../public/angular-svgrepo-com.svg"
import i2 from "../public/css3-02-svgrepo-com.svg"
import i3 from "../public/django-svgrepo-com.svg"
import i4 from "../public/docker-svgrepo-com.svg"
import i5 from "../public/flask-svgrepo-com.svg"
import i6 from "../public/html5-01-svgrepo-com.svg"
import i7 from "../public/java-svgrepo-com.svg"
import i8 from "../public/javascript-155-svgrepo-com.svg"
import i9 from "../public/kotlin-svgrepo-com.svg"
import i10 from "../public/kubernetes-svgrepo-com.svg"
import i11 from "../public/nextjs-icon-svgrepo-com.svg"
import i12 from "../public/node-fill-svgrepo-com.svg"
import i13 from "../public/python-127-svgrepo-com.svg"
import i14 from "../public/react-svgrepo-com.svg"
import i16 from "../public/svelte-16-svgrepo-com.svg"
import i17 from "../public/tailwind-svgrepo-com.svg"
import i18 from "../public/typescript-svgrepo-com.svg"
import i19 from "../public/vue-16-svgrepo-com.svg"

export const icons = [i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i16, i17, i18, i19]